/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CatalogueList.java
 *
 * Created on 31 mars 2013, 09:15:18
 */

package view;

import bean.Fournisseur;
import bean.Produit;
import dao.CatalogueItemDao;
import dao.FournisseurDao;
import dao.ProduitDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MoulayYounesSama
 */
public class FournisseurProducts extends javax.swing.JInternalFrame{

    private CatalogueistProduit catalogueParProduitParFournisseurHProd = new CatalogueistProduit();
    private CatalogueListFournisseur catalogueParProduitParFournisseurHFor = new CatalogueListFournisseur();
    private  CatalogueItemDao catalogueItemDao = new CatalogueItemDao();
    private FournisseurDao fournisseurDao= new FournisseurDao();
    private ProduitDao produitDao= new ProduitDao();
    
    /** Creates new form CatalogueList */
    public FournisseurProducts() {
        initComponents();
        this.setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ui = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        jTable2.setModel(catalogueParProduitParFournisseurHProd);
        jTable1.setModel(catalogueParProduitParFournisseurHFor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Libelle", "Famille", "Catégorie", "Unite", "Stock Max", "Stock Min", "Seuil Alert", "Prix", "TVA"
            }
        ));
        jTable2.setName("jTable2"); // NOI18N
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Societe", "Forme Juridique", "Personne a Contacter", "Adresse", "Tel Standard"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int recupererCodeProduit(){
        return   new Integer(""+catalogueParProduitParFournisseurHProd.getValueAt(jTable2.getSelectedRow(), 0));
    }
     private List<Integer> recupererAssocietForurnisseur(int codeProduit) throws SQLException{
         return catalogueItemDao.loadByCodeProduit(codeProduit);
    }

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
//        int codeProduit = recupererCodeProduit();
//        try {
//            List<Integer> associatedFor = recupererAssocietForurnisseur(codeProduit);
//            catalogueParProduitParFournisseurHFor.setFournisseurs(loadAllByCode(associatedFor));
//            catalogueParProduitParFournisseurHFor.fireTableDataChanged();
//        } catch (SQLException ex) {
//            Logger.getLogger(FournisseurProducts.class.getName()).log(Level.SEVERE, null, ex);
//        }

    
}//GEN-LAST:event_jTable2MouseClicked

       private List<Produit> loadAllProduitByCode(List<Integer> listCode,int codeForn) throws SQLException{
        return produitDao.loadAllByCode(listCode,codeForn);

    }
    private int recupererCodeFournisseur(){
        return   new Integer(""+catalogueParProduitParFournisseurHFor.getValueAt(jTable1.getSelectedRow(), 0));
    }
 private List<Integer> recupererAssocietProduit(int codeFornisseur) throws SQLException{
         return catalogueItemDao.loadByCodeFournisseur(codeFornisseur);
    }
  
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int codeForn = recupererCodeFournisseur();
        System.out.println("code for =="+codeForn);
        try {
            List<Integer> associatedProd = recupererAssocietProduit(codeForn);
            System.out.println("la list des produit est "+associatedProd);
            catalogueParProduitParFournisseurHProd.setProduits(loadAllProduitByCode(associatedProd, codeForn));
            catalogueParProduitParFournisseurHProd.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(FournisseurProducts.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FournisseurProducts().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
